### ISSUE TITLE
LogViewerController:index 在php8中报错

### ISSUE THREAD

**Issue by imwutao** [super-eggs/dcat-log-viewer#1]
应该把$file=null放在最后。还有日志查看是不是没有分页功能？
![image](https://user-images.githubusercontent.com/49136997/123015368-caa49300-d3fa-11eb-9e99-c65a49f9be27.png)
目录在全屏状态会导致串行

**Comment by super-eggs** [comment]
感谢反馈，会尽快修复。

**Comment by imwutao** [comment]
正在转接......
