### ISSUE TITLE
php8 报错

### ISSUE THREAD

**Issue by nantmpeter** [super-eggs/dcat-log-viewer#6]
SuperEggs\Dcat\LogViewer\Http\Controllers\LogViewerController::index(): Argument #2 ($request) must be of type Illuminate\Http\Request, Dcat\Admin\Layout\Content given, called in /Users/wangjiayi/westilt/projects/guagua/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54

php8 报错

**Comment by super-eggs** [comment]
1.0.3
